### PR TITLE
Get log what changes to working with stache bindings

### PR DESCRIPTION
**Pull request by m-mujica**
### How does it work?

1) `debug.makeDirectedGraph(obj, key)` does what the name implies (the graph for the full name example shown below), it associates metadata with each arrow/edge, where the dependency kind is stored. 

direct-graph-cycles

**NOTE** @justinbmeyer we talked about reversing the arrow between the heading (1) and ScopeKeyData (2).... But that would mean the heading has no dependencies hence 
`.logWhatChangesMe(heading)` would print nothing.

2) `debug.getDirectedAcyclicGraph(obj, key)` takes a directed graph (we could make this one from scratch instead of internally using `debug.makeDirectedGraph(obj, key)`, it'd be a lot faster, the directed graph -with cycles- is nice for drawing though)

There is a function in the graph, that returns a new one with the nodes/edges known to not have cycles, this function takes a callback that lets the caller decide what to do with the back edges.

can-debug provides a callback that given a back edge from B->A, checks if there is an edge from A -> B and adds the edge/metadata appropiately (a.k.a sets it as a `twoWay`)

The graph without cycles looks like:

dag

3) `debug.getDebugData(graphWithoutCycles)` creates a deeply nested data structure (I use this one for logging, I just could not figure out how to output the graph correctly with dfs/bfs)

output
 
### TO-DO LIST

- [x] - Implement the rest of the basic graph api to hide away the internal data structures (I'm missing `.getNodes`, `.getAdjacent`, `.hasEdge`
- [x] - Remove unused algorithms 😢 💔  (less code to maintain tho 🎊 )
- Extract logic to remove the cycles from the graph, it seems to be its own thing IMO
   (Update: not needed anymore since I got `getDirectedGraph` to remove cycles)
- [x] - Consistent API names (e.g `getDirectedAcyclicGraph` vs `makeDirectedGraph`)
- [x] - Fix tests

### Nice to have, but maybe later

- [x] - Make `debug.getDirectedAcyclicGraph(obj, key)` create the graph from scratch to avoid using `.makeDirectedGraph` (I think it's possible)

### CODE REVIEW

**Comment by justinbmeyer** [comment]
> NOTE @justinbmeyer we talked about reversing the arrow between the heading (1) and ScopeKeyData (2).... But that would mean the heading has no dependencies hence
.logWhatChangesMe(heading) would print nothing.

To be clear, (2) should be a "mutates" dependency of `(1)`.  Perhaps that doesn't change the arrows.  If not, anyway you could color them differently?  I think that might help things.

**Comment by m-mujica** [comment]
@justinbmeyer 

* dashed arrows are mutation deps
* single direction lines are regular deps
* to and from arrows are one A -> B edges flagged as two way

With cycles

direct-graph-cycles

Without

dag

**Comment by m-mujica** [comment]
Tests passing locally now.

The build will probably failed since I need to go through some of the deps and publish stuff (can-view-scope, can-stache-bindings).

google chrome

**Comment by m-mujica** [comment]
@justinbmeyer this is ready to review, before I merge this one. I need to merge and relase

- [ ] - https://github.com/canjs/can-view-scope/pull/118
- [ ] - https://github.com/canjs/can-stache-bindings/pull/340 (I feel this one needs more tests but not sure what to test exactly)

**Comment by m-mujica** [comment]
It now includes the logic to reverse the graph and log it (`logWhatIChange`).

**Comment by m-mujica** [comment]
I made the tests agnostic of stache, bindings and observables. So in theory this PR can be merged and release on its own.

`can-stache-bindings` is still listed as a dev dependency because it's needed by the graph visualization demo.

The screenshot below is the output and graph of `logWhatIChange` with the current state of `can-stache-bindings`. 

google chrome

**Comment by m-mujica** [comment]
Closed in favor of #17

**Pull request closed without merging**
